### ISSUE TITLE
It is not possible to import `anovos.feature_recommender.feature_recommendation` without first downloading the model

### ISSUE THREAD

**Issue by ionicsolutions** [anovos/anovos#105]
## Expected Behavior 

I can `import anovos.feature_recommender.feature_recommendation` without an Exception being raised.

(For example, when generating the API docs, see e.g. https://github.com/anovos/anovos-docs/runs/5379880799?check_suite_focus=true)

## Current Behavior

```shell
>>> import anovos.feature_recommender.feature_recommendation
2022-03-01 19:16:07.916613: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-01 19:16:07.916641: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kilian/Documents/Work/anovos/GitHub/anovos/src/main/anovos/feature_recommender/feature_recommendation.py", line 23, in <module>
    list_train_fer, df_rec_fer, list_embedding_train_fer = feature_recommendation_prep()
  File "/home/kilian/Documents/Work/anovos/GitHub/anovos/src/main/anovos/feature_recommender/featrec_init.py", line 217, in feature_recommendation_prep
    list_embedding_train_fer = model_fer.model.encode(
  File "/home/kilian/Documents/Work/anovos/GitHub/anovos/src/main/anovos/feature_recommender/featrec_init.py", line 52, in model
    raise FileNotFoundError(
FileNotFoundError: Model has not been downloaded. Please use model_download() function to download the model first
```

## Steps to reproduce

```shell
$ cd src/main
$ python

>>> import anovos.feature_recommender.feature_recommendation
```

### Specifications

- Version: current main state
- Platform: Ubuntu Linux (both locally and on GitHub Actions)
- Subsystem:

## Possible Solution

Completely solve #94 by not requiring the model at import time.

**Comment by kajanansangar** [comment]
@ionicsolutions as you can see from the error message that model_download() is a must-have prerequisite. Following is the error message shown

`FileNotFoundError: Model has not been downloaded. Please use model_download() function to download the model first`

**Comment by ionicsolutions** [comment]
Yes, I know, I wrote that code ;-)

Nevertheless, it should not be required to download anything in order to simply import Anovos without ever needing the model.

**Comment by kajanansangar** [comment]
other sub-modules of Anovos can be imported without any issue here @ionicsolutions But for this "feature_recommendation" import to work, the following sequence should be followed. As you remember that we do not want to download any models during the import too. 

`from anovos.feature_recommender.featrec_init import *`
 `model_download()`
`import anovos.feature_recommender.feature_recommendation`

**Comment by ionicsolutions** [comment]
I just added #108 which resolves this issue the same way we got around loading the model on import.
