### ISSUE TITLE
Doing `read_dataset` in `getting_started_with_anovos.ipynb` gives err

### ISSUE THREAD

**Issue by damiannmm** [anovos/anovos#39]
## Expected Behavior 

I'm not sure what to be expected, but at least it shouldn't returning Exception.

## Current Behavior

```py
from anovos.data_ingest.data_ingest import read_dataset

df = read_dataset(
    spark,  # Remember: The first argument of Anovos functions is always an instantiated SparkSession
    file_path='../data/income_dataset/csv',
    file_type='csv',
    file_configs={'header': 'True', 'delimiter': ',', 'inferSchema': 'True'}
)
```

Returns

```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
/tmp/ipykernel_235/916348546.py in <module>
      5     file_path='../data/income_dataset/csv',
      6     file_type='csv',
----> 7     file_configs={'header': 'True', 'delimiter': ',', 'inferSchema': 'True'}
      8 )

/opt/conda/lib/python3.7/site-packages/anovos/data_ingest/data_ingest.py in read_dataset(spark, file_path, file_type, file_configs)
     19     :return: Dataframe
     20     """
---> 21     odf = spark.read.format(file_type).options(**file_configs).load(file_path)
     22     return odf
     23 

/usr/local/spark/python/pyspark/sql/readwriter.py in load(self, path, format, schema, **options)
    156         self.options(**options)
    157         if isinstance(path, str):
--> 158             return self._df(self._jreader.load(path))
    159         elif path is not None:
    160             if type(path) != list:

/usr/local/spark/python/lib/py4j-0.10.9.2-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1308         answer = self.gateway_client.send_command(command)
   1309         return_value = get_return_value(
-> 1310             answer, self.gateway_client, self.target_id, self.name)
   1311 
   1312         for temp_arg in temp_args:

/usr/local/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    109     def deco(*a, **kw):
    110         try:
--> 111             return f(*a, **kw)
    112         except py4j.protocol.Py4JJavaError as e:
    113             converted = convert_exception(e.java_exception)

/usr/local/spark/python/lib/py4j-0.10.9.2-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o65.load.
: java.util.ServiceConfigurationError: org.apache.spark.sql.sources.DataSourceRegister: Provider org.apache.spark.sql.avro.AvroFileFormat could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:804)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:46)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:303)
	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:297)
	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:108)
	at scala.collection.TraversableLike.filter(TraversableLike.scala:395)
	at scala.collection.TraversableLike.filter$(TraversableLike.scala:395)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:108)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:652)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSourceV2(DataSource.scala:720)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:188)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoClassDefFoundError: org/apache/spark/sql/execution/datasources/FileFormat$class
	at org.apache.spark.sql.avro.AvroFileFormat.<init>(AvroFileFormat.scala:44)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780)
	... 31 more
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.execution.datasources.FileFormat$class
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 37 more
```

I'll put the link on shell output from installation to running (and having err) in this pastebin link: https://pastebin.com/WKwcWLnR

## Steps to reproduce

Run the `anovos-examples:latest` docker, go to `getting_started_with_anovos.ipynb` file. 13th line should gives this err.

### Specifications

(Everything is based on `./create_anovos_examples_docker_image.sh`'s docker)
- Version:
  + anovos 0.1
- Platform:
  + Python 3.7.12
  + Spark 3.2.0
  + Scala 2.12.15
- Subsystem:
  + Ubuntu Focal

## Possible Solution

Seems like something to do with either how Java or Spark is being set up.

**Comment by kajanansangar** [comment]
@damiannmm thanks much for testing. We are reproducing the bug and will get back with the root cause very soon

**Comment by damiannmm** [comment]
Thanks for the quick response!

**Comment by damiannmm** [comment]
Just wanna let you know that the result of running `./create_anovos_examples_docker_image.sh` is now

```bash
$ ./create_anovos_examples_docker_image.sh
Cloning into 'docker-stacks'...
remote: Enumerating objects: 212, done.
...
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
80b72a7086627591b0acad3b76b5c2236dd784cc7eca4bbded8d4e863b7fcff0
Python 3.7.12
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.4.8
      /_/

Using Scala version 2.11.12, OpenJDK 64-Bit Server VM, 1.8.0_312
...
```

So now it's using the expected spark version 2.4.8 and I can no longer found any err in the `getting_started_with_anovos.ipynb`

<img width="320" alt="Screen Shot 2022-01-04 at 3 45 23 PM" src="https://user-images.githubusercontent.com/1107336/148032683-f7c9bd84-7d9c-4c2c-a998-61a0e3a069c0.png">

**Comment by VishnuGowthem** [comment]
@damiannmm  thanks for the feedback.. 
we made a fix in the shell script to take the correct spark version in the docker, which was the cause of the issue. 

Alternatively, you can also pull the updated image from docker hub too 
```bash
sudo docker pull anovos/anovos-notebook-demo:0.1
sudo docker run -p 8888:8888 anovos/anovos-notebook-demo:0.1
```
and open the link to http://127.0.0.1:8888/?token... generated by the Jupyter NotebookApp

Also, similar to the getting started guide, 
there is also a series of notebooks to explore on each submodule under [notebooks/](https://github.com/anovos/anovos/tree/main/examples/notebooks) folder
and also a full end to end run demo in the [demo/](https://github.com/anovos/anovos/tree/main/demo/) folder 
Thanks
